./qoiconv assets/images_mono/alex.png build/images_mono/alex.qoi
./qoiconv assets/images_mono/alex_bg.png build/images_mono/alex_bg.qoi
./qoiconv assets/images_mono/alex_logo.png build/images_mono/alex_logo.qoi
./qoiconv assets/images_mono/all100.png build/images_mono/all100.qoi
./qoiconv assets/images_mono/bg0.png build/images_mono/bg0.qoi
./qoiconv assets/images_mono/bg1.png build/images_mono/bg1.qoi
./qoiconv assets/images_mono/bg2.png build/images_mono/bg2.qoi
./qoiconv assets/images_mono/bulb_bl.png build/images_mono/bulb_bl.qoi
./qoiconv assets/images_mono/bulb_br.png build/images_mono/bulb_br.qoi
./qoiconv assets/images_mono/bulb_tl.png build/images_mono/bulb_tl.qoi
./qoiconv assets/images_mono/bulb_tr.png build/images_mono/bulb_tr.qoi
./qoiconv assets/images_mono/bulba_bl.png build/images_mono/bulba_bl.qoi
./qoiconv assets/images_mono/bulba_br.png build/images_mono/bulba_br.qoi
./qoiconv assets/images_mono/bulba_tl.png build/images_mono/bulba_tl.qoi
./qoiconv assets/images_mono/bulba_tr.png build/images_mono/bulba_tr.qoi
./qoiconv assets/images_mono/bullet_1.png build/images_mono/bullet_1.qoi
./qoiconv assets/images_mono/bullet_2.png build/images_mono/bullet_2.qoi
./qoiconv assets/images_mono/cage_big.png build/images_mono/cage_big.qoi
./qoiconv assets/images_mono/cage_sml1.png build/images_mono/cage_sml1.qoi
./qoiconv assets/images_mono/cage_sml2.png build/images_mono/cage_sml2.qoi
./qoiconv assets/images_mono/chain.png build/images_mono/chain.qoi
./qoiconv assets/images_mono/cherry.png build/images_mono/cherry.qoi
./qoiconv assets/images_mono/chopper1.png build/images_mono/chopper1.qoi
./qoiconv assets/images_mono/chopper2.png build/images_mono/chopper2.qoi
./qoiconv assets/images_mono/chopper3.png build/images_mono/chopper3.qoi
./qoiconv assets/images_mono/chopper4.png build/images_mono/chopper4.qoi
./qoiconv assets/images_mono/drumcan.png build/images_mono/drumcan.qoi
./qoiconv assets/images_mono/egg.png build/images_mono/egg.qoi
./qoiconv assets/images_mono/egg2.png build/images_mono/egg2.qoi
./qoiconv assets/images_mono/enemy1_01.png build/images_mono/enemy1_01.qoi
./qoiconv assets/images_mono/enemy1_02.png build/images_mono/enemy1_02.qoi
./qoiconv assets/images_mono/enemy1_03.png build/images_mono/enemy1_03.qoi
./qoiconv assets/images_mono/enemy1_04.png build/images_mono/enemy1_04.qoi
./qoiconv assets/images_mono/enemy1_05.png build/images_mono/enemy1_05.qoi
./qoiconv assets/images_mono/enemy2_01.png build/images_mono/enemy2_01.qoi
./qoiconv assets/images_mono/enemy2_02.png build/images_mono/enemy2_02.qoi
./qoiconv assets/images_mono/enemy2_03.png build/images_mono/enemy2_03.qoi
./qoiconv assets/images_mono/enemy2_04.png build/images_mono/enemy2_04.qoi
./qoiconv assets/images_mono/enemy2_05.png build/images_mono/enemy2_05.qoi
./qoiconv assets/images_mono/enemy3.png build/images_mono/enemy3.qoi
./qoiconv assets/images_mono/enemy4.png build/images_mono/enemy4.qoi
./qoiconv assets/images_mono/enemy5_01.png build/images_mono/enemy5_01.qoi
./qoiconv assets/images_mono/enemy5_02.png build/images_mono/enemy5_02.qoi
./qoiconv assets/images_mono/enemy6.png build/images_mono/enemy6.qoi
./qoiconv assets/images_mono/fld_head.png build/images_mono/fld_head.qoi
./qoiconv assets/images_mono/fld_logo.png build/images_mono/fld_logo.qoi
./qoiconv assets/images_mono/game_over.png build/images_mono/game_over.qoi
./qoiconv assets/images_mono/guard1_1.png build/images_mono/guard1_1.qoi
./qoiconv assets/images_mono/guard1_2.png build/images_mono/guard1_2.qoi
./qoiconv assets/images_mono/guard1_3.png build/images_mono/guard1_3.qoi
./qoiconv assets/images_mono/guard1_4.png build/images_mono/guard1_4.qoi
./qoiconv assets/images_mono/guard1_5.png build/images_mono/guard1_5.qoi
./qoiconv assets/images_mono/guard1_6.png build/images_mono/guard1_6.qoi
./qoiconv assets/images_mono/guard1_7.png build/images_mono/guard1_7.qoi
./qoiconv assets/images_mono/guard1_8.png build/images_mono/guard1_8.qoi
./qoiconv assets/images_mono/guard2_1a.png build/images_mono/guard2_1a.qoi
./qoiconv assets/images_mono/guard2_1b.png build/images_mono/guard2_1b.qoi
./qoiconv assets/images_mono/guard2_2.png build/images_mono/guard2_2.qoi
./qoiconv assets/images_mono/guard2_3.png build/images_mono/guard2_3.qoi
./qoiconv assets/images_mono/guard2_4.png build/images_mono/guard2_4.qoi
./qoiconv assets/images_mono/guard2_5.png build/images_mono/guard2_5.qoi
./qoiconv assets/images_mono/guard2_6.png build/images_mono/guard2_6.qoi
./qoiconv assets/images_mono/heart.png build/images_mono/heart.qoi
./qoiconv assets/images_mono/heart2.png build/images_mono/heart2.qoi
./qoiconv assets/images_mono/hero000.png build/images_mono/hero000.qoi
./qoiconv assets/images_mono/hero001.png build/images_mono/hero001.qoi
./qoiconv assets/images_mono/hero002.png build/images_mono/hero002.qoi
./qoiconv assets/images_mono/hero003.png build/images_mono/hero003.qoi
./qoiconv assets/images_mono/hero_ball.png build/images_mono/hero_ball.qoi
./qoiconv assets/images_mono/hero_eat.png build/images_mono/hero_eat.qoi
./qoiconv assets/images_mono/hero_full.png build/images_mono/hero_full.qoi
./qoiconv assets/images_mono/hero_jump.png build/images_mono/hero_jump.qoi
./qoiconv assets/images_mono/hero_norm.png build/images_mono/hero_norm.qoi
./qoiconv assets/images_mono/hero_spit.png build/images_mono/hero_spit.qoi
./qoiconv assets/images_mono/intro_bg.png build/images_mono/intro_bg.qoi
./qoiconv assets/images_mono/letsgo.png build/images_mono/letsgo.qoi
./qoiconv assets/images_mono/levelcomplete.png build/images_mono/levelcomplete.qoi
./qoiconv assets/images_mono/lola.png build/images_mono/lola.qoi
./qoiconv assets/images_mono/oneup.png build/images_mono/oneup.qoi
./qoiconv assets/images_mono/particle_bopp.png build/images_mono/particle_bopp.qoi
./qoiconv assets/images_mono/particle_dust.png build/images_mono/particle_dust.qoi
./qoiconv assets/images_mono/pointer.png build/images_mono/pointer.qoi
./qoiconv assets/images_mono/ship0.png build/images_mono/ship0.qoi
./qoiconv assets/images_mono/ship1.png build/images_mono/ship1.qoi
./qoiconv assets/images_mono/ship100.png build/images_mono/ship100.qoi
./qoiconv assets/images_mono/smoke1.png build/images_mono/smoke1.qoi
./qoiconv assets/images_mono/smoke2.png build/images_mono/smoke2.qoi
./qoiconv assets/images_mono/smoke3.png build/images_mono/smoke3.qoi
./qoiconv assets/images_mono/smoke4.png build/images_mono/smoke4.qoi
./qoiconv assets/images_mono/smoke5.png build/images_mono/smoke5.qoi
./qoiconv assets/images_mono/smoke6.png build/images_mono/smoke6.qoi
./qoiconv assets/images_mono/smoke7.png build/images_mono/smoke7.qoi
./qoiconv assets/images_mono/smoke8.png build/images_mono/smoke8.qoi
./qoiconv assets/images_mono/spin1.png build/images_mono/spin1.qoi
./qoiconv assets/images_mono/spin2.png build/images_mono/spin2.qoi
./qoiconv assets/images_mono/spin3.png build/images_mono/spin3.qoi
./qoiconv assets/images_mono/spin4.png build/images_mono/spin4.qoi
./qoiconv assets/images_mono/star.png build/images_mono/star.qoi
./qoiconv assets/images_mono/tileset.png build/images_mono/tileset.qoi
./qoiconv assets/images_mono/ufo0.png build/images_mono/ufo0.qoi
./qoiconv assets/images_mono/ufo1.png build/images_mono/ufo1.qoi
./qoiconv assets/images_mono/ufo_big.png build/images_mono/ufo_big.qoi
./qoiconv assets/images_mono/ufobeam.png build/images_mono/ufobeam.qoi
./qoiconv assets/images_mono/water.png build/images_mono/water.qoi
./qoiconv assets/images_mono/water_surface.png build/images_mono/water_surface.qoi