magick assets/images_mono/alex.png -transparent "#3c8eaa" assets/images_mono/alex.png
magick assets/images_mono/alex_bg.png -transparent "#3c8eaa" assets/images_mono/alex_bg.png
magick assets/images_mono/alex_logo.png -transparent "#3c8eaa" assets/images_mono/alex_logo.png
magick assets/images_mono/all100.png -transparent "#3c8eaa" assets/images_mono/all100.png
magick assets/images_mono/bg0.png -transparent "#3c8eaa" assets/images_mono/bg0.png
magick assets/images_mono/bg1.png -transparent "#3c8eaa" assets/images_mono/bg1.png
magick assets/images_mono/bg2.png -transparent "#3c8eaa" assets/images_mono/bg2.png
magick assets/images_mono/bulb_bl.png -transparent "#3c8eaa" assets/images_mono/bulb_bl.png
magick assets/images_mono/bulb_br.png -transparent "#3c8eaa" assets/images_mono/bulb_br.png
magick assets/images_mono/bulb_tl.png -transparent "#3c8eaa" assets/images_mono/bulb_tl.png
magick assets/images_mono/bulb_tr.png -transparent "#3c8eaa" assets/images_mono/bulb_tr.png
magick assets/images_mono/bulba_bl.png -transparent "#3c8eaa" assets/images_mono/bulba_bl.png
magick assets/images_mono/bulba_br.png -transparent "#3c8eaa" assets/images_mono/bulba_br.png
magick assets/images_mono/bulba_tl.png -transparent "#3c8eaa" assets/images_mono/bulba_tl.png
magick assets/images_mono/bulba_tr.png -transparent "#3c8eaa" assets/images_mono/bulba_tr.png
magick assets/images_mono/bullet_1.png -transparent "#3c8eaa" assets/images_mono/bullet_1.png
magick assets/images_mono/bullet_2.png -transparent "#3c8eaa" assets/images_mono/bullet_2.png
magick assets/images_mono/cage_big.png -transparent "#3c8eaa" assets/images_mono/cage_big.png
magick assets/images_mono/cage_sml1.png -transparent "#3c8eaa" assets/images_mono/cage_sml1.png
magick assets/images_mono/cage_sml2.png -transparent "#3c8eaa" assets/images_mono/cage_sml2.png
magick assets/images_mono/chain.png -transparent "#3c8eaa" assets/images_mono/chain.png
magick assets/images_mono/cherry.png -transparent "#3c8eaa" assets/images_mono/cherry.png
magick assets/images_mono/chopper1.png -transparent "#3c8eaa" assets/images_mono/chopper1.png
magick assets/images_mono/chopper2.png -transparent "#3c8eaa" assets/images_mono/chopper2.png
magick assets/images_mono/chopper3.png -transparent "#3c8eaa" assets/images_mono/chopper3.png
magick assets/images_mono/chopper4.png -transparent "#3c8eaa" assets/images_mono/chopper4.png
magick assets/images_mono/drumcan.png -transparent "#3c8eaa" assets/images_mono/drumcan.png
magick assets/images_mono/egg.png -transparent "#3c8eaa" assets/images_mono/egg.png
magick assets/images_mono/egg2.png -transparent "#3c8eaa" assets/images_mono/egg2.png
magick assets/images_mono/enemy1_01.png -transparent "#3c8eaa" assets/images_mono/enemy1_01.png
magick assets/images_mono/enemy1_02.png -transparent "#3c8eaa" assets/images_mono/enemy1_02.png
magick assets/images_mono/enemy1_03.png -transparent "#3c8eaa" assets/images_mono/enemy1_03.png
magick assets/images_mono/enemy1_04.png -transparent "#3c8eaa" assets/images_mono/enemy1_04.png
magick assets/images_mono/enemy1_05.png -transparent "#3c8eaa" assets/images_mono/enemy1_05.png
magick assets/images_mono/enemy2_01.png -transparent "#3c8eaa" assets/images_mono/enemy2_01.png
magick assets/images_mono/enemy2_02.png -transparent "#3c8eaa" assets/images_mono/enemy2_02.png
magick assets/images_mono/enemy2_03.png -transparent "#3c8eaa" assets/images_mono/enemy2_03.png
magick assets/images_mono/enemy2_04.png -transparent "#3c8eaa" assets/images_mono/enemy2_04.png
magick assets/images_mono/enemy2_05.png -transparent "#3c8eaa" assets/images_mono/enemy2_05.png
magick assets/images_mono/enemy3.png -transparent "#3c8eaa" assets/images_mono/enemy3.png
magick assets/images_mono/enemy4.png -transparent "#3c8eaa" assets/images_mono/enemy4.png
magick assets/images_mono/enemy5_01.png -transparent "#3c8eaa" assets/images_mono/enemy5_01.png
magick assets/images_mono/enemy5_02.png -transparent "#3c8eaa" assets/images_mono/enemy5_02.png
magick assets/images_mono/enemy6.png -transparent "#3c8eaa" assets/images_mono/enemy6.png
magick assets/images_mono/fld_head.png -transparent "#3c8eaa" assets/images_mono/fld_head.png
magick assets/images_mono/fld_logo.png -transparent "#3c8eaa" assets/images_mono/fld_logo.png
magick assets/images_mono/game_over.png -transparent "#3c8eaa" assets/images_mono/game_over.png
magick assets/images_mono/guard1_1.png -transparent "#3c8eaa" assets/images_mono/guard1_1.png
magick assets/images_mono/guard1_2.png -transparent "#3c8eaa" assets/images_mono/guard1_2.png
magick assets/images_mono/guard1_3.png -transparent "#3c8eaa" assets/images_mono/guard1_3.png
magick assets/images_mono/guard1_4.png -transparent "#3c8eaa" assets/images_mono/guard1_4.png
magick assets/images_mono/guard1_5.png -transparent "#3c8eaa" assets/images_mono/guard1_5.png
magick assets/images_mono/guard1_6.png -transparent "#3c8eaa" assets/images_mono/guard1_6.png
magick assets/images_mono/guard1_7.png -transparent "#3c8eaa" assets/images_mono/guard1_7.png
magick assets/images_mono/guard1_8.png -transparent "#3c8eaa" assets/images_mono/guard1_8.png
magick assets/images_mono/guard2_1a.png -transparent "#3c8eaa" assets/images_mono/guard2_1a.png
magick assets/images_mono/guard2_1b.png -transparent "#3c8eaa" assets/images_mono/guard2_1b.png
magick assets/images_mono/guard2_2.png -transparent "#3c8eaa" assets/images_mono/guard2_2.png
magick assets/images_mono/guard2_3.png -transparent "#3c8eaa" assets/images_mono/guard2_3.png
magick assets/images_mono/guard2_4.png -transparent "#3c8eaa" assets/images_mono/guard2_4.png
magick assets/images_mono/guard2_5.png -transparent "#3c8eaa" assets/images_mono/guard2_5.png
magick assets/images_mono/guard2_6.png -transparent "#3c8eaa" assets/images_mono/guard2_6.png
magick assets/images_mono/heart.png -transparent "#3c8eaa" assets/images_mono/heart.png
magick assets/images_mono/heart2.png -transparent "#3c8eaa" assets/images_mono/heart2.png
magick assets/images_mono/hero000.png -transparent "#3c8eaa" assets/images_mono/hero000.png
magick assets/images_mono/hero001.png -transparent "#3c8eaa" assets/images_mono/hero001.png
magick assets/images_mono/hero002.png -transparent "#3c8eaa" assets/images_mono/hero002.png
magick assets/images_mono/hero003.png -transparent "#3c8eaa" assets/images_mono/hero003.png
magick assets/images_mono/hero_ball.png -transparent "#3c8eaa" assets/images_mono/hero_ball.png
magick assets/images_mono/hero_eat.png -transparent "#3c8eaa" assets/images_mono/hero_eat.png
magick assets/images_mono/hero_full.png -transparent "#3c8eaa" assets/images_mono/hero_full.png
magick assets/images_mono/hero_jump.png -transparent "#3c8eaa" assets/images_mono/hero_jump.png
magick assets/images_mono/hero_norm.png -transparent "#3c8eaa" assets/images_mono/hero_norm.png
magick assets/images_mono/hero_spit.png -transparent "#3c8eaa" assets/images_mono/hero_spit.png
magick assets/images_mono/intro_bg.png -transparent "#3c8eaa" assets/images_mono/intro_bg.png
magick assets/images_mono/letsgo.png -transparent "#3c8eaa" assets/images_mono/letsgo.png
magick assets/images_mono/levelcomplete.png -transparent "#3c8eaa" assets/images_mono/levelcomplete.png
magick assets/images_mono/lola.png -transparent "#3c8eaa" assets/images_mono/lola.png
magick assets/images_mono/oneup.png -transparent "#3c8eaa" assets/images_mono/oneup.png
magick assets/images_mono/particle_bopp.png -transparent "#3c8eaa" assets/images_mono/particle_bopp.png
magick assets/images_mono/particle_dust.png -transparent "#3c8eaa" assets/images_mono/particle_dust.png
magick assets/images_mono/pointer.png -transparent "#3c8eaa" assets/images_mono/pointer.png
magick assets/images_mono/ship0.png -transparent "#3c8eaa" assets/images_mono/ship0.png
magick assets/images_mono/ship1.png -transparent "#3c8eaa" assets/images_mono/ship1.png
magick assets/images_mono/ship100.png -transparent "#3c8eaa" assets/images_mono/ship100.png
magick assets/images_mono/smoke1.png -transparent "#3c8eaa" assets/images_mono/smoke1.png
magick assets/images_mono/smoke2.png -transparent "#3c8eaa" assets/images_mono/smoke2.png
magick assets/images_mono/smoke3.png -transparent "#3c8eaa" assets/images_mono/smoke3.png
magick assets/images_mono/smoke4.png -transparent "#3c8eaa" assets/images_mono/smoke4.png
magick assets/images_mono/smoke5.png -transparent "#3c8eaa" assets/images_mono/smoke5.png
magick assets/images_mono/smoke6.png -transparent "#3c8eaa" assets/images_mono/smoke6.png
magick assets/images_mono/smoke7.png -transparent "#3c8eaa" assets/images_mono/smoke7.png
magick assets/images_mono/smoke8.png -transparent "#3c8eaa" assets/images_mono/smoke8.png
magick assets/images_mono/spin1.png -transparent "#3c8eaa" assets/images_mono/spin1.png
magick assets/images_mono/spin2.png -transparent "#3c8eaa" assets/images_mono/spin2.png
magick assets/images_mono/spin3.png -transparent "#3c8eaa" assets/images_mono/spin3.png
magick assets/images_mono/spin4.png -transparent "#3c8eaa" assets/images_mono/spin4.png
magick assets/images_mono/star.png -transparent "#3c8eaa" assets/images_mono/star.png
magick assets/images_mono/tileset.png -transparent "#3c8eaa" assets/images_mono/tileset.png
magick assets/images_mono/ufo0.png -transparent "#3c8eaa" assets/images_mono/ufo0.png
magick assets/images_mono/ufo1.png -transparent "#3c8eaa" assets/images_mono/ufo1.png
magick assets/images_mono/ufo_big.png -transparent "#3c8eaa" assets/images_mono/ufo_big.png
magick assets/images_mono/ufobeam.png -transparent "#3c8eaa" assets/images_mono/ufobeam.png
magick assets/images_mono/water.png -transparent "#3c8eaa" assets/images_mono/water.png
magick assets/images_mono/water_surface.png -transparent "#3c8eaa" assets/images_mono/water_surface.png