./qoaconv assets/sfx_22/cherry.wav ./build/sfx_22/cherry.qoa
./qoaconv assets/sfx_22/chopper.wav ./build/sfx_22/chopper.qoa
./qoaconv assets/sfx_22/crush.wav ./build/sfx_22/crush.qoa
./qoaconv assets/sfx_22/die.wav ./build/sfx_22/die.qoa
./qoaconv assets/sfx_22/eat.wav ./build/sfx_22/eat.qoa
./qoaconv assets/sfx_22/energy.wav ./build/sfx_22/energy.qoa
./qoaconv assets/sfx_22/engine.wav ./build/sfx_22/engine.qoa
./qoaconv assets/sfx_22/heart.wav ./build/sfx_22/heart.qoa
./qoaconv assets/sfx_22/hit.wav ./build/sfx_22/hit.qoa
./qoaconv assets/sfx_22/hurt.wav ./build/sfx_22/hurt.qoa
./qoaconv assets/sfx_22/impact.wav ./build/sfx_22/impact.qoa
./qoaconv assets/sfx_22/jump.wav ./build/sfx_22/jump.qoa
./qoaconv assets/sfx_22/kill.wav ./build/sfx_22/kill.qoa
./qoaconv assets/sfx_22/menu.wav ./build/sfx_22/menu.qoa
./qoaconv assets/sfx_22/pause.wav ./build/sfx_22/pause.qoa
./qoaconv assets/sfx_22/point.wav ./build/sfx_22/point.qoa
./qoaconv assets/sfx_22/ship.wav ./build/sfx_22/ship.qoa
./qoaconv assets/sfx_22/shoot.wav ./build/sfx_22/shoot.qoa
./qoaconv assets/sfx_22/spit.wav ./build/sfx_22/spit.qoa
./qoaconv assets/sfx_22/star.wav ./build/sfx_22/star.qoa
./qoaconv assets/sfx_22/startup.wav ./build/sfx_22/startup.qoa
./qoaconv assets/sfx_22/stomp.wav ./build/sfx_22/stomp.qoa
./qoaconv assets/sfx_22/talk.wav ./build/sfx_22/talk.qoa
./qoaconv assets/sfx_22/turn.wav ./build/sfx_22/turn.qoa
./qoaconv assets/sfx_22/xtralife.wav ./build/sfx_22/xtralife.qoa
./qoaconv assets/music/GAME.wav ./build/music/GAME.qoa
